# Generated by Django 4.2.11 on 2024-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devedores',
            name='data_pagamento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='devedores',
            name='pagou',
            field=models.BooleanField(default=False),
        ),
    ]
