# Generated by Django 4.2.11 on 2024-04-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portApp', '0002_devedores_data_pagamento_devedores_pagou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devedores',
            name='cliente',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devedores',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='devedores',
            name='divida',
            field=models.FloatField(null=True),
        ),
    ]
