# Generated by Django 4.2.11 on 2024-04-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portApp', '0004_alter_devedores_cliente_alter_devedores_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devedores',
            old_name='data_pagamento',
            new_name='data_modificacao',
        ),
    ]
